{{ $appName := .Release.Name }}
{{- with .Values.app }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $appName }}-ingress
spec:
  defaultBackend:
    service:
      name: {{ $appName }}-svc
      port:
        number: {{ .port }}
{{- end }}
