{{ $appName := .Release.Name }}
{{ $app := .Values.app }}
{{- range .Values.app.variants }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-{{ .name }}-deployment
  labels:
    app: {{ $appName }}
    version: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ $appName }}
      version: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
        version: {{ .name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ $app.metrics.port }}"
    spec:
      containers:
        - name: {{ $appName }}
          image: "ghcr.io/remla23-team14/app:{{ .version }}"
          ports:
            - name: 'app'
              containerPort: {{ $app.port }}
            - name: 'metrics'
              containerPort: {{ $app.metrics.port }}
          env:
            - name: MODEL_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ $appName }}-cm
                  key: model-service.host
            - name: ENABLE_METRICS
              value: '{{ $app.metrics.enabled }}'
            - name: METRICS_PORT
              value: '{{ $app.metrics.port }}'
---
{{- end }}
