{{ $appName := .Release.Name }}
{{- with .Values.app }}
{{- if .metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $appName }}-monitor
  labels:
    app: {{ $appName }}-svc
    release: {{ $appName}}
spec:
  jobLabel: {{ $appName }}-svc
  selector:
    matchLabels:
      app: {{ $appName }}-svc
  endpoints:
  - interval: 1s
    path: '/metrics'
    port: 'metrics'
{{- end }}
{{- end }}
