{{ $appName := .Release.Name }}
{{- with .Values.app }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-svc
  labels:
    app: {{ $appName }}-svc
spec:
  selector:
    app: {{ $appName }}
  ports:
    - name: 'http-app'
      port: {{ .port }}
      targetPort: {{ .port }}
    {{- if .metrics.enabled }}
    - name: 'http-metrics'
      port: {{ .metrics.port }}
      targetPort: {{ .metrics.port }}
    {{- end }}
{{- end }}
