{{ $appName := .Release.Name }}
{{- with .Values.app }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-svc
spec:
  selector:
    app: {{ $appName }}
  ports:
    - name: 'app'
      port: {{ .port }}
      targetPort: {{ .port }}
    {{- if .metrics.enabled }}
    - name: 'metrics'
      port: {{ .metrics.port }}
      targetPort: {{ .metrics.port }}
    {{- end }}
{{- end }}
