services:
  model-service:
    image: ghcr.io/remla23-team14/model-service
    expose:
      - "8080"
  app:
    image: ghcr.io/remla23-team14/app
    ports:
      - "80:8080"
    environment:
      - MODEL_SERVICE_URL=http://model-service:8080
    depends_on:
      - model-service
