services:
  model-service:
    image: ghcr.io/remla23-team14/model-service
    expose:
      - "8080"
    volumes:
#      - ./model-training/c1_BoW_Sentiment_Model.pkl:/root/model-training/c1_BoW_Sentiment_Model.pkl
#      - ./model-training/c2_Classifier_Sentiment_Model:/root/model-training/c2_Classifier_Sentiment_Model
#      - ./model-training/pre_processed_dataset.joblib:/root/model-training/pre_processed_dataset.joblib
#      - ./model-training/model_metrics.json:/root/model-training/model_metrics.json
  app:
    image: ghcr.io/remla23-team14/app
    ports:
      - "80:8080"
    environment:
      MODEL_SERVICE_URL: http://model-service:8080
#      DVC_REPO: "https://github.com/remla23-team14/model-training.git"
#      DVC_REV: "HEAD"
#      DVC_MODEL_PATH: "models/c2_Classifier_Sentiment_Model"
#      DVC_PREPROCESSOR_PATH: "data/processed/c1_BoW_Sentiment_Model.joblib"
#      DVC_CORPUS_PATH: "data/processed/pre_processed_dataset.joblib"
#      DVC_METRICS_PATH: "data/output/model_metrics.json"
#      USE_DVC: "false"
    depends_on:
      - model-service
