# monitoring.yml
apiVersion: v1
kind: Pod
metadata:
  name: model-service
  labels:
    app: model-service
spec:
  containers:
  - name: model-service
    image: ghcr.io/remla23-team14/model-service:latest
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: model-service-serv
  labels:
    app: model-service-serv
spec:
  type: NodePort
  selector:
    app: model-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-model-monitor
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: model-service-serv
  endpoints:
  - interval: 1s
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
spec:
  containers:
  - name: app
    image: ghcr.io/remla23-team14/app:latest
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-serv
  labels:
    app: app-serv
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 9091
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: app-serv
  endpoints:
  - interval: 1s