modelService:
  version: latest
  port: 8080
  metrics:
    enabled: true
    port: 9091
  replicas: 1

app:
  version: latest
  port: 8080
  metrics:
    enabled: true
    port: 9091
  replicas: 1

prometheus:
  enabled: true
  host: 'prometheus.local'
  port: 9090

grafana:
  enabled: true
  host: 'grafana.local'
  port: 3000
