{
 "title": "App",
 "description": "Dashboard to be used for the project. Contains useful information about the application",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Deployment accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "deployment_accuracy", "legendFormat": "Deployment accuracy" }
   ]
  },
  {
   "title": "Last Confidence score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "last_confidence_score", "legendFormat": "Confidence score" }
   ]
  },
  {
   "title": "App Page Visits total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "app_page_visits{path=~\"/|/restaurants\"}",
     "legendFormat": "{{method}}: {{path}}"
    },
    {
     "expr": "app_page_visits{path!~\"/|/restaurants\"}",
     "legendFormat": "{{method}}: {{restaurantName}}"
    }
   ]
  },
  {
   "title": "App Page Visits per min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(app_page_visits[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (method, path, restaurantName) (increase(app_page_visits{path=~\"/|/restaurants\"}[1m]))",
     "legendFormat": "{{method}}: {{path}}"
    },
    {
     "expr": "sum by (method, path, restaurantName) (increase(app_page_visits{path!~\"/|/restaurants\"}[1m]))",
     "legendFormat": "{{method}}: {{restaurantName}}"
    }
   ]
  }
 ]
}