{
 "title": "App_info",
 "description": "Dashboard to be used for the project. Contains useful information about the application",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Deployment accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "deployment_accuracy", "legendFormat": "Deployment accuracy" }
   ]
  },
  {
   "title": "Last Confidence score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "last_confidence_score", "legendFormat": "Confidence score" }
   ]
  },
  {
   "title": "Visits per Page",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "app_page_visits",
     "legendFormat": "{{restaurantName}} {{method}} {{path}} "
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "changes(app_page_visits[1m])",
     "legendFormat": "{{restaurantName}} {{method}} {{path}} "
    }
   ]
  }
 ]
}