{{ $modelServiceName := print .Release.Name "-model-service" }}
{{- with .Values.modelService }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $modelServiceName }}-deployment
  labels:
    app: {{ $modelServiceName }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ $modelServiceName }}
  template:
    metadata:
      labels:
        app: {{ $modelServiceName }}
      annotations:
        prometheus.io/scrape: "{{ .metrics.enabled }}"
        prometheus.io/port: "{{ .port }}"
    spec:
      containers:
        - name: {{ $modelServiceName }}
          image: "ghcr.io/remla23-team14/model-service:{{ .version }}"
          ports:
            - name: 'model-service'
              containerPort: {{ .port }}
          {{- with .localModel }}
          {{- if .enabled }}
          volumeMounts:
            - mountPath: '/root/model-training/c1_BoW_Sentiment_Model.pkl'
              name: {{ $modelServiceName }}-vectorizer-volume
            - mountPath: '/root/model-training/c2_Classifier_Sentiment_Model'
              name: {{ $modelServiceName }}-model-volume
          {{- end }}
          {{- end }}
      {{- with .localModel }}
      {{- if .enabled }}
      volumes:
        - name: {{ $modelServiceName }}-vectorizer-volume
          hostPath:
            path: '{{ .vectorizerPath }}'
            type: 'File'
        - name: {{ $modelServiceName }}-model-volume
          hostPath:
            path: '{{ .modelPath }}'
            type: 'File'
      {{- end }}
      {{- end }}
{{- end }}
