{{ $modelServiceName := print .Release.Name "-model-service" }}
{{- with .Values.modelService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $modelServiceName }}-svc
  labels:
    app: {{ $modelServiceName }}-svc
spec:
  selector:
    app: {{ $modelServiceName }}
  ports:
    - name: 'model-service'
      port: {{ .port }}
      targetPort: {{ .port }}
    {{- if .metrics.enabled }}
    - name: 'metrics'
      port: {{ .metrics.port }}
      targetPort: {{ .metrics.port }}
    {{- end }}
{{- end }}
