{{ $modelServiceName := print .Release.Name "-model-service" }}
{{- with .Values.modelService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $modelServiceName }}-svc
  labels:
    app: {{ $modelServiceName }}-svc
spec:
  selector:
    app: {{ $modelServiceName }}
  ports:
    - name: 'http-model-service'
      port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}
