{{ $appName := .Release.Name }}
{{- with .Values.prometheus }}
{{- if .enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $appName }}-prometheus-entry-service
spec:
  gateways:
    - {{ $appName }}-gateway
  hosts:
    - '{{ .host }}'
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: prometheus.istio-system.svc.cluster.local
            port:
              number: {{ .port }}
{{- end }}
{{- end }}
