{{ $appName := .Release.Name }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $appName}}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"




{{/*{{ $appName := .Release.Name }}*/}}
{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: {{ $appName }}-ingress*/}}
{{/*spec:*/}}
{{/*  rules:*/}}
{{/*  {{- with .Values.prometheus }}*/}}
{{/*  {{- if .enabled }}*/}}
{{/*  - host: '{{ .host }}'*/}}
{{/*    http:*/}}
{{/*      paths:*/}}
{{/*      - path: '/'*/}}
{{/*        pathType: Prefix*/}}
{{/*        backend:*/}}
{{/*          service:*/}}
{{/*            name: {{ $appName }}-kube-prometheus-stack-prometheus*/}}
{{/*            port:*/}}
{{/*              number: {{ .port }}*/}}
{{/*  {{- end }}*/}}
{{/*  {{- end }}*/}}

{{/*  {{- with .Values.grafana }}*/}}
{{/*    {{- if .enabled }}*/}}
{{/*  - host: '{{ .host }}'*/}}
{{/*    http:*/}}
{{/*      paths:*/}}
{{/*      - path: '/'*/}}
{{/*        pathType: Prefix*/}}
{{/*        backend:*/}}
{{/*          service:*/}}
{{/*            name: {{ $appName }}-grafana*/}}
{{/*            port:*/}}
{{/*              number: {{ .port }}*/}}
{{/*    {{- end }}*/}}
{{/*    {{- end }}*/}}

{{/*  {{- with .Values.app }}*/}}
{{/*  - http:*/}}
{{/*      paths:*/}}
{{/*      - path: '/'*/}}
{{/*        pathType: Prefix*/}}
{{/*        backend:*/}}
{{/*          service:*/}}
{{/*            name: {{ $appName }}-svc*/}}
{{/*            port:*/}}
{{/*              number: {{ .port }}*/}}
{{/*  {{- end }}*/}}
