{{ $appName := .Release.Name }}
{{ $prometheusName := print $appName "-prometheus" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $prometheusName }}-app.rules
  labels:
    release: {{ $appName }}
spec:
  groups:
    - name: app.rules
      rules:
        - alert: HighRequestRate
          expr: sum(increase(app_page_visits[1m])) > 15
          for: 2m
          labels:
            severity: 'page'
          annotations:
            summary: High request rate
            description: The app service has been receiving more than 15 requests per minute for the last two minutes.
