name: Release Charts
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Update Chart.yaml
        run: |
          TAG="${{ github.ref_name }}"
          VERSION="${TAG:1}"
          git checkout main
          for f in $(find . -name 'Chart.yaml'); do echo "$f"; done
          find . -name 'Chart.yaml' -exec yq -i ".version = \"${VERSION}\"" {} \;
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
      - name: Commit Chart.yaml
        run: |
          TAG="${{ github.ref_name }}"
          VERSION="${TAG:1}"
          git checkout main
          git commit -am "Update Chart.yaml version to $VERSION"
          git push
          git tag -f "$TAG"
          git push origin -f "$TAG"
